version: '3.7'

services:
  front:
    container_name: front
    build: ./front
    ports:
      - "8000:80"
    environment:
      WS_URL: ws://0.0.0.0:8080

  back:
    container_name: back
    build: ./back
    ports:
      - "8080:8080"
